const TEAMS = [
  {id: 1, name: "Egypt", url: "egypt", group: "A", price: 9 },
  {id: 2, name: "Russia", url: "russia", group: "A", price: 13 },
  {id: 3, name: "Saudi Arabia", url: "saudi-arabia", group: "A", price: 2 }, 
  {id: 4, name: "Uruguay", url: "uruguay", group: "A", price: 17 },
  {id: 5, name: "Iran", url: "iran", group: "B", price: 2 },
  {id: 6, name: "Morocco", url: "morocco", group: "B", price: 3 },
  {id: 7, name: "Portugal", url: "portugal", group: "B", price: 25 },
  {id: 8, name: "Spain", url: "spain", group: "B", price: 32 },
  {id: 9, name: "Australia", url: "australia", group: "C", price: 4 },
  {id: 10, name: "Denmark", url: "denmark", group: "C", price: 9 },
  {id: 11, name: "France", url: "france", group: "C", price: 30 },
  {id: 12, name: "Peru", url: "peru", group: "C", price: 6 },
  {id: 13, name: "Argentina", url: "argentina", group: "D", price: 28 },
  {id: 14, name: "Croatia", url: "croatia", group: "D", price: 12 },
  {id: 15, name: "Iceland", url: "iceland", group: "D", price: 5 },
  {id: 16, name: "Nigeria", url: "nigeria", group: "D", price: 7 },
  {id: 17, name: "Brazil", url: "brazil", group: "E", price: 35 },
  {id: 18, name: "Costa Rica", url: "costa-rica", group: "E", price: 4 },
  {id: 19, name: "Serbia", url: "serbia", group: "E", price: 7 },
  {id: 20, name: "Switzerland", url: "switzerland", group: "E", price: 9 },
  {id: 21, name: "Germany", url: "germany", group: "F", price: 35 },
  {id: 22, name: "Mexico", url: "mexico", group: "F", price: 11 },
  {id: 23, name: "Sweden", url: "sweden", group: "F", price: 8 },
  {id: 24, name: "South Korea", url: "south-korea", group: "F", price: 3 },
  {id: 25, name: "Belgium", url: "belgium", group: "G", price:  22},
  {id: 26, name: "England", url: "england", group: "G", price:  20},
  {id: 27, name: "Panama", url: "panama", group: "G", price:  1},
  {id: 28, name: "Tunisia", url: "tunisia", group: "G", price: 2 },
  {id: 29, name: "Colombia", url: "colombia", group: "H", price: 17 },
  {id: 30, name: "Japan", url: "japan", group: "H", price:  8},
  {id: 31, name: "Poland", url: "poland", group: "H", price: 13 },
  {id: 32, name: "Senegal", url: "senegal", group: "H", price: 9 },

];

export default TEAMS;