const TEAMS = [
  {id: 1, name: "Egypt", continent: "Africa", url: "egypt", group: "A", price: 8, selected: false },
  {id: 2, name: "Russia", continent: "Europe", url: "russia", group: "A", price: 15, selected: false },
  {id: 3, name: "Saudi Arabia", continent: "Asia", url: "saudi-arabia", group: "A", price: 2, selected: false }, 
  {id: 4, name: "Uruguay", continent: "South America", url: "uruguay", group: "A", price: 19, selected: false },
  {id: 5, name: "Iran", continent: "Asia", url: "iran", group: "B", price: 3, selected: false },
  {id: 6, name: "Morocco", continent: "Africa", url: "morocco", group: "B", price: 5, selected: false },
  {id: 7, name: "Portugal", continent: "Europe", url: "portugal", group: "B", price: 22, selected: false },
  {id: 8, name: "Spain", continent: "Europe", url: "spain", group: "B", price: 30, selected: false },
  {id: 9, name: "Australia", continent: "Asia", url: "australia", group: "C", price: 4, selected: false },
  {id: 10, name: "Denmark", continent: "Europe", url: "denmark", group: "C", price: 10, selected: false },
  {id: 11, name: "France", continent: "Europe", url: "france", group: "C", price: 29, selected: false },
  {id: 12, name: "Peru", continent: "South America", url: "peru", group: "C", price: 6, selected: false },
  {id: 13, name: "Argentina", continent: "South America", url: "argentina", group: "D", price: 27, selected: false },
  {id: 14, name: "Croatia", continent: "Europe", url: "croatia", group: "D", price: 12, selected: false },
  {id: 15, name: "Iceland", continent: "Europe", url: "iceland", group: "D", price: 5, selected: false },
  {id: 16, name: "Nigeria", continent: "Africa", url: "nigeria", group: "D", price: 7, selected: false },
  {id: 17, name: "Brazil", continent: "South America", url: "brazil", group: "E", price: 33, selected: false },
  {id: 18, name: "Costa Rica", continent: "North America", url: "costa-rica", group: "E", price: 4, selected: false },
  {id: 19, name: "Serbia", continent: "Europe", url: "serbia", group: "E", price: 7, selected: false },
  {id: 20, name: "Switzerland", continent: "Europe", url: "switzerland", group: "E", price: 9, selected: false },
  {id: 21, name: "Germany", continent: "Europe", url: "germany", group: "F", price: 33, selected: false },
  {id: 22, name: "Mexico", continent: "North America", url: "mexico", group: "F", price: 10, selected: false },
  {id: 23, name: "Sweden", continent: "Europe", url: "sweden", group: "F", price: 8, selected: false },
  {id: 24, name: "South Korea", continent: "Asia", url: "south-korea", group: "F", price: 3, selected: false },
  {id: 25, name: "Belgium", continent: "Europe", url: "belgium", group: "G", price: 24, selected: false },
  {id: 26, name: "England", continent: "Europe", url: "england", group: "G", price: 21, selected: false },
  {id: 27, name: "Panama", continent: "North America", url: "panama", group: "G", price: 1, selected: false },
  {id: 28, name: "Tunisia", continent: "Africa", url: "tunisia", group: "G", price: 2, selected: false },
  {id: 29, name: "Colombia", continent: "South America", url: "colombia", group: "H", price: 18, selected: false },
  {id: 30, name: "Japan", continent: "Asia", url: "japan", group: "H", price:  6, selected: false },
  {id: 31, name: "Poland", continent: "Europe", url: "poland", group: "H", price: 14, selected: false },
  {id: 32, name: "Senegal", continent: "Africa", url: "senegal", group: "H", price: 7, selected: false },

];

export default TEAMS;