const TEAMS = [
  {name: "Egypt", url: "egypt", group: "A", price: 9 },
  {name: "Russia", url: "russia", group: "A", price: 13 },
  {name: "Saudi Arabia", url: "saudi-arabia", group: "A", price: 2 }, 
  {name: "Uruguay", url: "uruguay", group: "A", price: 17 },
  {name: "Iran", url: "iran", group: "B", price: 2 },
  {name: "Morocco", url: "morocco", group: "B", price: 3 },
  {name: "Portugal", url: "portugal", group: "B", price: 25 },
  {name: "Spain", url: "spain", group: "B", price: 32 },
  {name: "Australia", url: "australia", group: "C", price: 4 },
  {name: "Denmark", url: "denmark", group: "C", price: 9 },
  {name: "France", url: "france", group: "C", price: 30 },
  {name: "Peru", url: "peru", group: "C", price: 6 },
  {name: "Argentina", url: "argentina", group: "D", price: 28 },
  {name: "Croatia", url: "croatia", group: "D", price: 12 },
  {name: "Iceland", url: "iceland", group: "D", price: 5 },
  {name: "Nigeria", url: "nigeria", group: "D", price: 7 },
  {name: "Brazil", url: "brazil", group: "E", price: 35 },
  {name: "Costa Rica", url: "costa-rica", group: "E", price: 4 },
  {name: "Serbia", url: "serbia", group: "E", price: 7 },
  {name: "Switerland", url: "switzerland", group: "E", price: 9 },
  {name: "Germany", url: "germany", group: "F", price: 35 },
  {name: "Mexico", url: "mexico", group: "F", price: 11 },
  {name: "Sweden", url: "sweden", group: "F", price: 8 },
  {name: "South Korea", url: "south-korea", group: "F", price: 3 },
  {name: "Belgium", url: "belgium", group: "G", price:  22},
  {name: "England", url: "england", group: "G", price:  20},
  {name: "Panama", url: "panama", group: "G", price:  1},
  {name: "Tunisia", url: "tunisia", group: "G", price: 2 },
  {name: "Colombia", url: "colombia", group: "H", price: 17 },
  {name: "Japan", url: "japan", group: "H", price:  8},
  {name: "Poland", url: "poland", group: "H", price: 13 },
  {name: "Senegal", url: "senegal", group: "H", price: 9 },

];

export default TEAMS;